### ISSUE TITLE
Problem statement does not load

### ISSUE THREAD

**Issue by Hialus** [ls1intum/artemis-ios#109]
## Description:
The app does not display the problem statement (checked for programming & quiz exercises)

## Screenshots
In the app:
![IMG_3181](https://github.com/ls1intum/artemis-ios/assets/18218285/5e0a00a0-3ca5-4441-b290-2501387943b4)

On the website:
![image](https://github.com/ls1intum/artemis-ios/assets/18218285/4a618c2c-662e-45cd-8516-ebd967439490)

**Comment by maximiliansoelch** [comment]
Caused by route changes in the Artemis Web Client: https://github.com/ls1intum/Artemis/pull/8246
