### ISSUE TITLE
App crashes after re-entering a chat channel

### ISSUE THREAD

**Issue by JanaNF** [ls1intum/artemis-ios#179]
To reproduce:
1. Open App
2. Go to a course (e.g, ITP)
3. Go to "Messages"
4. Click on a text channel (e.g. private channel)
5. Swip left/ leave channel
6. Click on a different text channel
7. The app crashes so that you see the home screen of your iPhone

**Comment by anian03** [comment]
Which version of the app are you experiencing this issue on? You can see the version number in iOS Settings > General > iPhone Storage > Artemis.
If this is version 1.2.0 or below, please check whether updating the app resolves the issue :)
