### ISSUE TITLE
Inconsistent labeling between exercises and lectures

### ISSUE THREAD

**Issue by robertjndw** [ls1intum/artemis-ios#184]
The labeling between exercises and lectures is inconsistent (e.g., `1 Exercise` vs `Lectures: 1`). See the attached screenshots for reference. Standardizing the naming conventions would help improve clarity and reduce confusion.
<p float="left">
<img src="https://github.com/user-attachments/assets/01e7261f-ea42-4a6c-813a-4d7bae368856" width=150 />
<img src="https://github.com/user-attachments/assets/c67c986a-cf63-45a6-b638-46999a1376b7" width=150 />
</p>

**Comment by anian03** [comment]
Thanks, missed that when updating it. Fixing it right now
