### ISSUE TITLE
Restrict Message Resolving

### ISSUE THREAD

**Issue by Abus00** [ls1intum/artemis-ios#190]
# Feature Request: Restrict Message Resolving to Original Question Asker or Tutor

**Description:**
Currently, any student can resolve a message, even if they were not the one who asked the original question. This has led to situations where other students have incorrectly marked their own (false) answer as "resolving the question". 

**Proposed Feature:**
- Only the student who originally asked the question should be able to mark the tutor’s reply as resolved.
- Other students should not have the ability to resolve questions posed by their peers, ensuring only the question asker can confirm the tutor’s response as resolved.

**Expected Benefits:**
- Prevents incorrect resolutions.
- Ensures that only the student who asked the question can confirm the answer is satisfactory.

**Comment by anian03** [comment]
Hey, would it be possible for you to provide an example scenario for when this issue occurs?
I haven't been able to reproduce this behavior, as a student I am only able to resolve a thread if I asked the initial question.

So right now users can resolve a thread if they asked the original question or if they are a tutor, which appears to align with your suggestion.

**Comment by Abus00** [comment]
Hi, I apologize for the confusion. It appears that this issue is only affecting the web version. I initially thought it was also occurring on the iOS version. I'm sorry for the inconvenience.

**Comment by anian03** [comment]
Alright, no worries! Glad it works correctly on iOS :)
