### ISSUE TITLE
Feature Request: Pinning Messages 

### ISSUE THREAD

**Issue by Abus00** [ls1intum/artemis-ios#193]
# Feature Request: Pinning Messages on iOS

## Description:
I would like to request the implementation of a "pin messages" feature for the iOS app, similar to the web version. This feature would allow tutors and intructors pin important messages within a conversation.

## Proposed Features
1. **Pin Messages Functionality:**
   - Tutors and instructors should have the ability to pin any message in the chat
   - Pinned messages should remain accessible throughout the conversation.

2. **Pinned Messages Icon:**
   - A small icon on the top navigation bar that allows users to view all pinned messages in a list or popup.
  
This would allow easy acces to important info and would help students to quickly navigate to commonly asked questions

**Comment by anian03** [comment]
Pinning messages is already supported in the iOS app (context menu in chat and quick actions bar in thread view) for supported user roles, and pinned messages are highlighted with a yellow background the the chat transcript.

It is not currently possible to only display pinned messages, the only supported filters by the server are Unresolved, Own and Reacted. These are added to iOS in #225. If you'd like to be able to filter for pinned messages as well, I'd recommend opening a feature request for it in https://github.com/ls1intum/Artemis. We can then also add it to the iOS app without issues :)
