### ISSUE TITLE
Unkwon Decoding Issue 

### ISSUE THREAD

**Issue by JanaNF** [ls1intum/artemis-ios#253]
Right now there is not enough information but to put attention to it I created the issue. Hopefully, I am going to add new screenshots.
![image](https://github.com/user-attachments/assets/92149585-17c4-4211-ae3d-1f5b8455a376)

**Comment by anian03** [comment]
This has to be a server side race condition or something… I got this today, with the first 256 Byte block being fine, and then the second block being just garbage.
![IMG_3166](https://github.com/user-attachments/assets/8006e372-ea47-41bd-82d9-a9af5ca4d5e6)

**Comment by anian03** [comment]
Fixed by https://github.com/ls1intum/Artemis/pull/10060.
Only group chat notifications are probably still broken due to `null` being part of an array of non optional
