### ISSUE TITLE
Thread Notification in Private Groupe Chat Leads to "Feature Not Implemented" Error

### ISSUE THREAD

**Issue by JanaNF** [ls1intum/artemis-ios#257]
I received a notification that someone replied to me. It indicated that it was a thread reply in a private groupe chat.

## Steps to Reproduce:
1. I clicked on the notification.
2. The app opened and displayed the following message:
3. "This feature is not implemented. Open Web/Cancel" (or something similar, you probably know the exact message).
4. After checking, the notification was supposed to open a thread related to one of my meme messages.
5. The chat in question is a private course chat among tutors and instructors.

## Additional Notes:
- This happened in a private course chat, not in a public chat.
- This is the first time I received a thread notification. I cannot confirm if this issue occurs consistently.

**Comment by anian03** [comment]
Cause: Notification target sent by server is `/courses/:courseId/message/:messageId`. This does not include the conversation id, thus the client does not know where to navigate. (The server doesn't seem to know either 😂)
