### ISSUE TITLE
Missing Recated Emoji in the app which is seen in the webpage 

### ISSUE THREAD

**Issue by JanaNF** [ls1intum/artemis-ios#258]
The app sometimes doesn't show reacted emojis. I have seen this in a private group chat. I tried to re-enter the chat and restart the app, but nothing worked.

Issue could be emoji library.

Webpage:
![image](https://github.com/user-attachments/assets/540ea2dd-a56d-4f2b-824d-f2b6130a6265)
Vs app:
![image](https://github.com/user-attachments/assets/7263e4c8-64df-4499-a69d-2ef0220850da)

Webpage:
![image](https://github.com/user-attachments/assets/1a4b0405-e360-4669-88f2-c67adccc81a9)
Vs app:
![image](https://github.com/user-attachments/assets/608a95c3-48a0-4baf-88a1-4008cb00be2c)

**Comment by anian03** [comment]
Our emoji library uses different names for Emojis than the one in the web app.
🤯 is `mindblown` on iOS and `exploding_head` in the web app. Not sure what to do here to be honest

**Comment by anian03** [comment]
Update: Found a version of our library that seems to use more correct name descriptions. Switching to that.
