### ISSUE TITLE
Scrolling Occasionally Fails on iOS (Potential Gesture Conflict)

### ISSUE THREAD

**Issue by JanaNF** [ls1intum/artemis-ios#259]
## Problem:
Sometimes scrolling doesn’t work properly. I need several attempts to scroll up.

## Possible Cause:
It seems like the system might think I’m trying to swipe left due to the focus on the message. This results in a poor user experience.

## Additional Notes:
- This issue has been present since iOS 18.
- Increasing the gesture threshold for other actions might resolve the problem, as suggested by @anian03.

**Comment by anian03** [comment]
Yup, this is an iOS 18 issue. There is no official workaround. This got broken and never fixed.

Will try replacing the swipe gesture with a simultaneousGesture (that way, scrolling will always work), but I need to figure out how to only have one of the gestures (scroll/swipe) active at once.
