### ISSUE TITLE
Too many web socket connections

### ISSUE THREAD

**Issue by sven0311** [ls1intum/artemis-ios#33]
Beforehand, clients opened to many web socket connections, especially for the notifications. Therefore, changes were made to the server and web client to reduce the web socket subscriptions and improve the performance. See [this PR](https://github.com/ls1intum/Artemis/pull/6697/files) for the changes made. 

This changes now need to be adapted to the Artemis iOS app as well. In detail the `NotificationWebsocketServiceImpl` needs to be adapted to the new web socket topic and handle incoming messages appropriately.

**Comment by nityanandaz** [comment]
See #64
